services:
  - docker

env:
  global:
    - TEST_MODE=1
    - DOCKER_COMPOSE_ETC='./dev/devdocker/'
    - CONF_FILE=/tmp/

os: linux

dist: focal

language: python

python:
  - '3.7'

# safelist branch to build
branches:
  only:
    - master

install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - unit_tests
  - integration_tests
  - factory_tests

notifications:
  email:
    - bifer@alea-soluciones.com
