services:
  - docker

env:
  global:
    - TEST_MODE=1
    - DOCKER_COMPOSE_ETC='./dev/devdocker/'
    - CONF_FILE=/tmp/

os: linux

dist: focal

language: python

python:
  - '3.7'

branches:
  only:
    - master

install:
  - python -m pip install --no-cache-dir --upgrade pip wheel setuptools
  - python -m pip install --no-cache-dir -r requirements-versioned.txt
  - python -m pip install --no-cache-dir -r requirements-dev.txt
  - python -m pip install -e .

script:
  - unit_tests
  - integration_tests
  - factory_tests

notifications:
  email:
    - bifer@alea-soluciones.com
