sudo: required

services:
- docker

env:
    global:
        - TEST_MODE=1

language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
python:
  - '3.7'

# safelist branch to build
branches:
  only:
      - master

before_install:
  - sudo apt-get -y update || true

install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - ./dev/unit_tests.sh
  - ./dev/integration_tests.sh
  - ./dev/factory_tests.sh

notifications:
  email:
    - bifer@alea-soluciones.com
